import './globals.css'
import { Inter } from 'next/font/google'
import styles from './globals.module.css'
import NavBar from './components/NavBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={styles.outerContainer}>
          <img className={styles.banner} src="" alt="banner"></img>
          <NavBar />
          {children}
        </div>
      </body>
    </html>
  )
}
